# Configuration for request-info - https://github.com/behaviorbot/request-info

# *Required* Comment to reply with
requestInfoReplyComment: |
  Hi there :wave:!

  I noticed that this new issue/PR doesn't provide any description, so I labeled it with `needs-more-info`.
  
  In order for us to be able to review your contribution and answer questions more quickly, please
  describe it in more detail. A thorough description will also help people from the future, who
  are looking for some quick context around this set of changes.

  A great way to start is to follow <a href="https://github.com/jupyterhub/.github/tree/master/.github/ISSUE_TEMPLATE">issue templates</a> or the repository specific
  PR template (if any). Ultimately, the most important question to answer in your
  description is: *what goal do you want to achieve with this change?*.

  Thank you! :heart:

# *OPTIONAL* default titles to check against for lack of descriptiveness
# MUST BE ALL LOWERCASE
requestInfoDefaultTitles:
  - update readme.md
  - updates

# *OPTIONAL* Label to be added to Issues and Pull Requests with insufficient information given
requestInfoLabelToAdd: needs-more-info

###

# Configuration for welcome - https://github.com/behaviorbot/welcome

# Configuration for new-issue-welcome - https://github.com/behaviorbot/new-issue-welcome

# Comment to be posted to on first time issues
newIssueWelcomeComment: >
  Thanks for opening your first issue in this project! Your input is very important to us! :hugs:

  <br>If you haven't done so already, check out our [Code of Conduct](https://github.com/jupyter/governance/blob/master/conduct/code_of_conduct.md).
  Also, please make sure you followed the issue templates, as this will help us provide feedback more quickly.

  ![welcome](https://raw.githubusercontent.com/jupyterhub/.github/master/images/welcome.jpg)

  You can meet the other [Jovyans](https://jupyter.readthedocs.io/en/latest/community/content-community.html?highlight=jovyan#what-is-a-jovyan)
  by joining our [Discourse forum](http://discourse.jupyter.org/). There is also a intro thread there where you can stop by and say Hi! :wave:

  <br>Welcome to the Jupyter community! :tada:

# Configuration for new-pr-welcome - https://github.com/behaviorbot/new-pr-welcome

# Comment to be posted to on PRs from first time contributors in your repository
newPRWelcomeComment: >
  Thanks for submitting your first pull request! You are awesome! :hugs:

  <br>If you haven't done so already, check out our [Code of Conduct](https://github.com/jupyter/governance/blob/master/conduct/code_of_conduct.md).
  Also, please make sure you followed the pull request template, as this will help us review your contribution more quickly.

  ![welcome](https://raw.githubusercontent.com/jupyterhub/.github/master/images/welcome.jpg)

  You can meet the other [Jovyans](https://jupyter.readthedocs.io/en/latest/community/content-community.html?highlight=jovyan#what-is-a-jovyan)
  by joining our [Discourse forum](http://discourse.jupyter.org/). There is also a intro thread there where you can stop by and say Hi! :wave:

  <br>Welcome to the Jupyter community! :tada:

# Configuration for first-pr-merge - https://github.com/behaviorbot/first-pr-merge

# Comment to be posted to on pull requests merged by a first time user
firstPRMergeComment: >
  Congrats on your first merged pull request in this project! :tada:

  ![congrats](https://raw.githubusercontent.com/jupyterhub/.github/master/images/congrats.jpg)

  Thank you for contributing, we are very proud of you! :heart:
