# Configuration for request-info - https://github.com/behaviorbot/request-info

# *Required* Comment to reply with
requestInfoReplyComment: |
  Hi there :wave:!

  We would appreciate it if you could provide us with more info about this issue/PR.
  A great way to start would be to follow the <a href="https://github.com/jupyterhub/.github/tree/master/.github/ISSUE_TEMPLATE">issue templates</a> or the repository
  specific PR template (if any).
  
  This helps people review your contribution and answer questions more quickly and also
  helps people in the future who are looking for some quick context around this set of changes.

  Thank you! :heart:

# *OPTIONAL* default titles to check against for lack of descriptiveness
# MUST BE ALL LOWERCASE
requestInfoDefaultTitles:
  - update readme.md
  - updates

# *OPTIONAL* Label to be added to Issues and Pull Requests with insufficient information given
requestInfoLabelToAdd: needs-more-info
